[workspace]
resolver = "2"
members = ["bambam", "bambam-osm", "bambam-util", "bambam-overturemaps"]

[workspace.dependencies]
kdam = "0.6.2"
bamcensus-core = { git = "https://github.com/NREL/bamcensus.git", branch = "main" }
bamcensus-acs = { git = "https://github.com/NREL/bamcensus.git", branch = "main" }
bamcensus = { git = "https://github.com/NREL/bamcensus.git", branch = "main" }
bamcensus-lehd = { git = "https://github.com/NREL/bamcensus.git", branch = "main" }
routee-compass = { version = "0.11.3" }
routee-compass-core = { version = "0.11.3" }
routee-compass-powertrain = { version = "0.11.3" }
compass-tomtom = { git = "https://github.nrel.gov/MBAP/routee-compass-tomtom.git", branch = "release/v0.4.0" }
