[workspace]
resolver = "2"
members = ["bambam", "bambam-osm", "bambam-util"]

[workspace.dependencies]
kdam = "0.6.2"
bamsoda-core = { git = "https://github.nrel.gov/BAM/bamsoda.git", branch = "main" }
bamsoda-acs = { git = "https://github.nrel.gov/BAM/bamsoda.git", branch = "main" }
bamsoda-app = { git = "https://github.nrel.gov/BAM/bamsoda.git", branch = "main" }
bamsoda-lehd = { git = "https://github.nrel.gov/BAM/bamsoda.git", branch = "main" }
routee-compass = { git = "https://github.com/NREL/routee-compass.git", version = "0.9.1" }
routee-compass-core = { git = "https://github.com/NREL/routee-compass.git", version = "0.9.1" }
routee-compass-powertrain = { git = "https://github.com/NREL/routee-compass.git", version = "0.9.1" }
compass-tomtom = { git = "https://github.nrel.gov/MBAP/routee-compass-tomtom.git", branch = "rjf/update-units" }
