[[search]] # WALK TOPOLOGY
traversal.type = "combined"
traversal.models = [
    { type = "distance", distance_unit = "miles" }, 
    { type = "fixed_speed", name = "edge", speed = 5.0, speed_unit = "kph" },
    { type = "time", time_unit = "minutes" },
    { type = "multimodal", mode = "walk" }
]
access.type = "combined"
access.models = [
    { type = "multimodal", mode = "walk" }
]
frontier.type = "combined"
frontier.models = [
    { type = "road_class", road_class_input_file = "../denver_co/edges-road-class-enumerated.txt.gz" },
    { type = "time_limit", time_limit = { time = 40.0, time_unit = "minutes" }}
]

[[search]] # BIKE TOPOLOGY
traversal.type = "combined"
traversal.models = [
    { type = "distance", distance_unit = "miles" }, 
    { type = "fixed_speed", name = "edge", speed = 16.0, speed_unit = "kph" },
    { type = "time", time_unit = "minutes" },
    { type = "multimodal", mode = "bike" }
]
access.type = "combined"
access.models = [
    { type = "multimodal", mode = "bike" }
]
frontier.type = "combined"
frontier.models = [
    { type = "road_class", road_class_input_file = "../denver_co/edges-road-class-enumerated.txt.gz" },
    { type = "time_limit", time_limit = { time = 40.0, time_unit = "minutes" }}
]

[[search]] # DRIVE TOPOLOGY
traversal.type = "combined"
traversal.models = [
    { type = "distance", distance_unit = "miles" }, 
    { type = "speed", speed_table_input_file = "../denver_co/edges-posted-speed-enumerated.txt.gz", speed_unit = "kph" },
    { type = "time", time_unit = "minutes" },
    { type = "multimodal", mode = "drive" }
]
access.type = "combined"
access.models = [
    { type = "multimodal", mode = "drive" }
]
frontier.type = "combined"
frontier.models = [
    { type = "road_class", road_class_input_file = "../denver_co/edges-road-class-enumerated.txt.gz" },
    { type = "time_limit", time_limit = { time = 40.0, time_unit = "minutes" }}
]

[[search]] # TRANSIT TOPOLOGY
traversal.type = "combined"
traversal.models = [
    { type = "distance", distance_unit = "miles" }, 
    { type = "gtfs", gtfs_directory = "../denver_co/gtfs", calendar_policy = { type = "nearest", date = "2025-09-17" } },
    { type = "multimodal", mode = "transit" }
]
access.type = "combined"
access.models = [
    { type = "multimodal", mode = "transit" }
]
frontier.type = "combined"
frontier.models = [
    { type = "road_class", road_class_input_file = "../denver_co/edges-road-class-enumerated.txt.gz" },
    { type = "time_limit", time_limit = { time = 40.0, time_unit = "minutes" }}
]