[graph]
vertex_list_input_file = "vertices-compass.csv.gz"
edge_list = [
    { input_file = "walk/edges-compass.csv.gz" },
    { input_file = "bike/edges-compass.csv.gz" },
    { input_file = "drive/edges-compass.csv.gz" },
    { input_file = "gtfs/archive-0001-edges-compass.csv.gz" },
]

###
### WALK TOPOLOGY
###
[[search]] 
traversal.type = "combined"
traversal.models = [
    { type = "distance", distance_unit = "miles" }, 
    { type = "fixed_speed", name = "walk", speed = 5.0, speed_unit = "kph" },
    { type = "time", time_unit = "minutes" },
    { type = "multimodal", mode = "walk", available_modes = ["walk", "bike", "drive", "transit-archive-0001"], available_route_ids = [], use_route_ids = false }
]

frontier.type = "combined"
frontier.models = [
    { type = "road_class", road_class_input_file = "walk/edges-walk-road-class-enumerated.txt.gz" },
    { type = "time_limit", time_limit = { time = 40.0, time_unit = "minutes" }},
    { type = "multimodal", constraints = [], available_modes = ["walk", "bike", "drive", "transit-archive-0001"], available_route_ids = [], use_route_ids = false }
]

###
### BIKE TOPOLOGY
###
[[search]] 
traversal.type = "combined"
traversal.models = [
    { type = "distance", distance_unit = "miles" }, 
    { type = "fixed_speed", name = "bike", speed = 16.0, speed_unit = "kph" },
    { type = "time", time_unit = "minutes" },
    { type = "multimodal", mode = "bike", available_modes = ["walk", "bike", "drive", "transit-archive-0001"], available_route_ids = [], use_route_ids = false }
]
frontier.type = "combined"
frontier.models = [
    { type = "road_class", road_class_input_file = "bike/edges-bike-road-class-enumerated.txt.gz" },
    { type = "time_limit", time_limit = { time = 40.0, time_unit = "minutes" }},
    { type = "multimodal", constraints = [], available_modes = ["walk", "bike", "drive", "transit-archive-0001"], available_route_ids = [], use_route_ids = false }
]
###
### DRIVE TOPOLOGY
###
[[search]] 
traversal.type = "combined"
traversal.models = [
    { type = "distance", distance_unit = "miles" }, 
    { type = "speed", speed_table_input_file = "drive/edges-posted-speed-enumerated.txt.gz", speed_unit = "kph" },
    { type = "time", time_unit = "minutes" },
    { type = "multimodal", mode = "drive", available_modes = ["walk", "bike", "drive", "transit-archive-0001"], available_route_ids = [], use_route_ids = false }
]
frontier.type = "combined"
frontier.models = [
    { type = "road_class", road_class_input_file = "drive/edges-road-class-enumerated.txt.gz" },
    { type = "time_limit", time_limit = { time = 40.0, time_unit = "minutes" }},
    { type = "multimodal", constraints = [], available_modes = ["walk", "bike", "drive", "transit-archive-0001"], available_route_ids = [], use_route_ids = false }
]

###
### TRANSIT TOPOLOGY
###
[[search]] 
traversal.type = "combined"
traversal.models = [
    { type = "distance", distance_unit = "miles" }, 
    { type = "gtfs", gtfs_directory = "gtfs/archive-0001.zip", calendar_policy = { type = "nearest", date = "2025-09-17" } },
    { type = "multimodal", mode = "transit-archive-0001", available_modes = ["walk", "bike", "drive", "transit-archive-0001"], available_route_ids = ["A", "B", "C"], use_route_ids = true }
]

frontier.type = "combined"
frontier.models = [
    { type = "time_limit", time_limit = { time = 40.0, time_unit = "minutes" }},
    { type = "multimodal", constraints = [], available_modes = ["walk", "bike", "drive", "transit-archive-0001"], available_route_ids = [], use_route_ids = false }
]