name: Auto Ready for Review

on:
  pull_request:
    types: [closed]

jobs:
  auto_ready_draft:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Extract dependent PR number
        id: extract_pr
        run: |
          PR_BODY="${{ github.event.pull_request.body }}"
          DEPENDENT_PR=$(echo "$PR_BODY" | grep -oP 'Depends on #\K\d+')
          if [ -n "$DEPENDENT_PR" ]; then
            echo "Dependent PR found: $DEPENDENT_PR"
            echo "dependent_pr=$DEPENDENT_PR" >> $GITHUB_OUTPUT
          else
            echo "No dependent PR found."
          fi

      - name: Mark dependent PR as ready for review
        if: steps.extract_pr.outputs.dependent_pr != ''
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr ready ${{ steps.extract_pr.outputs.dependent_pr }}