name: Publish - crates.io

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to Crates.io
    environment: crates
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Formatting
        run: |
          rustup component add rustfmt
          cargo fmt --all --manifest-path rust/Cargo.toml -- --check
          
      - name: Install test assets
        run: |
          ./setup.sh

      - name: Test
        run: |
          cargo test --workspace --verbose --manifest-path rust/Cargo.toml

      - name: Publish bambam-osm
        run: cargo publish -p bambam-osm --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"

      - name: Publish bambam-gtfs
        run: cargo publish -p bambam-gtfs --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"

      - name: Publish bambam-overturemaps
        run: cargo publish -p bambam-overturemaps --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"

      - name: Publish bambam
        run: cargo publish -p bambam --manifest-path=rust/Cargo.toml --token "${{ secrets.CRATES_IO_TOKEN }}"

