name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          cache: false

      - name: Formatting
        run: |
          rustup component add rustfmt
          cargo fmt --all --manifest-path rust/Cargo.toml -- --check

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Install test assets
        run: |
          ./script/setup_test_bambam.sh  
          ./script/setup_test_bambam_osm.sh

      - name: Cargo test
        run: |
          cargo test --workspace --verbose --manifest-path rust/Cargo.toml

      - name: End-to-end GTFS BAMBAM test
        run: |
          ./script/run_gtfs_test.sh
