name: Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    name: cargo test
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Formatting
        run: |
          rustup component add rustfmt
          cargo fmt --all --manifest-path rust/Cargo.toml -- --check
          
      - name: Install test assets
        run: |
          ./setup.sh

      - name: Test
        run: |
          cargo test --workspace --verbose --manifest-path rust/Cargo.toml
